[2024-10-16T06:27:22.380+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2024-10-16T06:20:00+00:00 [queued]>
[2024-10-16T06:27:22.385+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2024-10-16T06:20:00+00:00 [queued]>
[2024-10-16T06:27:22.385+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T06:27:22.385+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-10-16T06:27:22.385+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-10-16T06:27:22.391+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-10-16 06:20:00+00:00
[2024-10-16T06:27:22.393+0000] {standard_task_runner.py:55} INFO - Started process 2702 to run task
[2024-10-16T06:27:22.395+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2024-10-16T06:20:00+00:00', '--job-id', '396', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpof_csp8a']
[2024-10-16T06:27:22.395+0000] {standard_task_runner.py:83} INFO - Job 396: Subtask is_api_available
[2024-10-16T06:27:22.421+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2024-10-16T06:20:00+00:00 [running]> on host b35d88915934
[2024-10-16T06:27:22.450+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-10-16T06:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-16T06:20:00+00:00
[2024-10-16T06:27:22.450+0000] {http.py:120} INFO - Poking: api/
[2024-10-16T06:27:22.454+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2024-10-16T06:27:22.455+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2024-10-16T06:27:22.873+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/urllib3/connectionpool.py:1052: InsecureRequestWarning: Unverified HTTPS request is being made to host 'randomuser.me'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

[2024-10-16T06:27:23.232+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2024-10-16T06:27:23.245+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20241016T062000, start_date=20241016T062722, end_date=20241016T062723
[2024-10-16T06:27:23.265+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-10-16T06:27:23.287+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
